---
bantuGlobalChristianTexts2027: 'Bantu, Vince, and Nathan P. Gibson, eds. Global Christian
  Texts: Readings in Premodern Christianity from African, Middle Eastern, and Asian
  Languages. De Gruyter Studium. Berlin: De Gruyter Brill, 2027.'
ConnectingLateAntiquities2025: H-Soz-Kult. Kommunikation und Fachinformation für die
  Geschichtswissenschaften. “Connecting Late Antiquities | H-Soz-Kult. Kommunikation
  und Fachinformation für die Geschichtswissenschaften | Geschichte im Netz | History
  in the web.” H-Soz-Kult, May 19, 2025. https://www.hsozkult.de/conferencereport/id/fdkn-155043.
duckerJeGrosserLiebe2023: 'Dücker, Malte. “‘Je größer die Liebe und Nähe (zwischen
  Nachbarn), desto mehr Hass und Entfremdung kann es geben.’ : Interview zur Berufung
  von Prof. Dr. Nathan Gibson.” Jahrbuch des Fachbereichs Evangelische Theologie der
  Goethe-Universität Frankfurt am Main 3 (2023): 32–33. https://doi.org/10.21248/gups.80437.'
ghorbaninejadRighttoLeftRTLText2023: 'Ghorbaninejad, Masoud, Nathan P. Gibson, and
  David Joseph Wrisley. “Right-to-Left (RTL) Text: Digital Humanists Plus Half a Billion
  Users.” In Debates in the Digital Humanities 2023, edited by Matthew K. Gold and
  Lauren F. Klein, 47–73. Debates in the Digital Humanities 9. Minneapolis: University
  of Minnesota Press, 2023. https://dhdebates.gc.cuny.edu/read/debates-in-the-digital-humanities-2023/section/51ad75ab-76a4-43f3-81f8-0b31e350ca9c#ch03.'
gibsonAbrahamPointDeparture2012: "———. “Abraham as a Point of Departure in the ‘Monk
  of Bet Hale’ Text.” July 16, 2012."
gibsonAlJahizDivineAdoption2022: 'Gibson, Nathan P., and Ronny Vollandt. “Cross-Communal
  Scholarly Interactions.” In Routledge Handbook on the Sciences in Islamicate Societies:
  Practices from the 2nd/8th to the 13th/19th Centuries, edited by Sonja Brentjes,
  Peter Barker, and Rana Brentjes, 723–40. Routledge Handbooks. London: Routledge,
  2022. https://doi.org/10.4324/9781315170718-65.'
gibsonArabicLiteraryPersonages2023: 'Dücker, Malte. “‘Je größer die Liebe und Nähe
  (zwischen Nachbarn), desto mehr Hass und Entfremdung kann es geben.’ : Interview
  zur Berufung von Prof. Dr. Nathan Gibson.” Jahrbuch des Fachbereichs Evangelische
  Theologie der Goethe-Universität Frankfurt am Main 3 (2023): 32–33. https://doi.org/10.21248/gups.80437.'
gibsonAuthorityRecordsFrontiers2021: "———. “Authority Records at the Frontiers of
  Research: How Can Small Projects Incorporate Large Providers into Their Workflows?”
  October 28, 2021. http://npgibson.com/s/authority-frontiers."
gibsonBibleArabicUpdate2018: 'Dücker, Malte. “‘Je größer die Liebe und Nähe (zwischen
  Nachbarn), desto mehr Hass und Entfremdung kann es geben.’ : Interview zur Berufung
  von Prof. Dr. Nathan Gibson.” Jahrbuch des Fachbereichs Evangelische Theologie der
  Goethe-Universität Frankfurt am Main 3 (2023): 32–33. https://doi.org/10.21248/gups.80437.'
gibsonChallengesPolyvalentInfrastructures2017: "“Balisage.” Accessed March 31, 2017.
  http://www.balisage.net/Proceedings/vol16/html/Gibson01/BalisageVol16-Gibson01.html."
gibsonChristianOrientIslamic2017: "“Balisage.” Accessed March 31, 2017. http://www.balisage.net/Proceedings/vol16/html/Gibson01/BalisageVol16-Gibson01.html."
gibsonCircumnavigatingJewishChristian2022: "———. “Circumnavigating Jewish and Christian
  Realities: What the Polemicist al-Jāḥiẓ Didn’t Want to Admit about His Society.”
  November 11, 2022. http://npgibson.com/s/circumnavigating."
gibsonClosestFriendshipAlJahiz2015: "“BibBase.” Accessed March 5, 2019. https://bibbase.org/network/publication/gibson-closestinfriendshipaljahizprofileofchristiansinabbasidsocietyintherefutationofchristiansalraddalaalnasara-2015."
gibsonCommunitiesKnowledgeInterreligious2020: "———, ed. Communities of Knowledge:
  Interreligious Networks of Scholars in Ibn Abi Usaybiʿa’s History of the Physicians.
  Version 0.4. Munich: Usaybia.net, 2020. https://doi.org/10.5281/zenodo.3975505."
gibsonCommunitiesKnowledgeInterreligious2023a: 'Dücker, Malte. “‘Je größer die Liebe
  und Nähe (zwischen Nachbarn), desto mehr Hass und Entfremdung kann es geben.’ :
  Interview zur Berufung von Prof. Dr. Nathan Gibson.” Jahrbuch des Fachbereichs Evangelische
  Theologie der Goethe-Universität Frankfurt am Main 3 (2023): 32–33. https://doi.org/10.21248/gups.80437.'
gibsonCommunitiesKnowledgeUsaybianet2020: "———. “Communities of Knowledge (Usaybia.Net):
  Tagging, Prosopography, and Networks.” October 20, 2020."
gibsonCrosscommunalScholarlyInteractions2022: "“Gibson and Vollandt - 2023 - Cross-Communal
  Scholarly Interactions.Pdf,” n.d."
gibsonCyberinfrastructureSyriacLiterature2017: "“Balisage.” Accessed March 31, 2017.
  http://www.balisage.net/Proceedings/vol16/html/Gibson01/BalisageVol16-Gibson01.html."
gibsonDistantReadingPersons2020: "———. “Distant Reading for Persons and Networks.”
  June 9, 2020."
gibsonDivineAdoptionJewish2023: 'Dücker, Malte. “‘Je größer die Liebe und Nähe (zwischen
  Nachbarn), desto mehr Hass und Entfremdung kann es geben.’ : Interview zur Berufung
  von Prof. Dr. Nathan Gibson.” Jahrbuch des Fachbereichs Evangelische Theologie der
  Goethe-Universität Frankfurt am Main 3 (2023): 32–33. https://doi.org/10.21248/gups.80437.'
gibsonEncodingWesternNonWestern2015: Gibson, Nathan P., Winona Salesky, and David
  A. Michelson. “Encoding Western and Non-Western Names for Ancient Syriac Authors.”
  In Proceedings of the Symposium on Cultural Heritage Markup. Balisage Series on
  Markup Technologies 16. Washington, D.C., 2015. https://doi.org/10.4242/BalisageVol16.Gibson01.
gibsonEntityTaggingNetwork2024: "“Full Text PDF.” Accessed March 18, 2024. http://publikationen.ub.uni-frankfurt.de/files/80437/09_Gibson_Duecker.pdf."
gibsonFiveCenturiesHistory2019: 'Dücker, Malte. “‘Je größer die Liebe und Nähe (zwischen
  Nachbarn), desto mehr Hass und Entfremdung kann es geben.’ : Interview zur Berufung
  von Prof. Dr. Nathan Gibson.” Jahrbuch des Fachbereichs Evangelische Theologie der
  Goethe-Universität Frankfurt am Main 3 (2023): 32–33. https://doi.org/10.21248/gups.80437.'
gibsonFlorilegiumBadTranslations2016: 'Gibson, Nathan P. “A Florilegium of Bad Translations:
  Al-Jahiz’s Ninth-Century Excerpts of Jewish Arabic Bible Translations.” March 29,
  2016.'
gibsonGodAloneKnows2024: "“Full Text PDF.” Accessed March 18, 2024. http://publikationen.ub.uni-frankfurt.de/files/80437/09_Gibson_Duecker.pdf."
gibsonGospelCitationsVirgin2012: "———. “Gospel Citations on the Virgin Birth from
  Ninth Century Muslim Writers.” July 19, 2012."
gibsonGuideSyriacaorgReference2016: "———. “A Guide to Syriaca.Org Reference Tools
  and Desiderata for Central and East Asia.” June 19, 2016."
gibsonInquiringBeelzebubChristians2013: "———. “Inquiring of ‘Beelzebub’: Christians
  between the Caliph’s Courts and the ‘Kingdom of God.’” November 23, 2013."
gibsonInterreligiousContactsAbbasid2017: "“Balisage.” Accessed March 31, 2017. http://www.balisage.net/Proceedings/vol16/html/Gibson01/BalisageVol16-Gibson01.html."
gibsonIslamicScholarPluralistic2016: "———. “An Islamic Scholar in a Pluralistic Society:
  The Biography of al-Jahiz Reconsidered.” April 11, 2016."
gibsonKnowledgeCollaborationJews2022: "———. “Knowledge Collaboration among Jews, Christians,
  Zoroastrians, and Muslims in the Abbasid Near East: Introduction.” Medieval Worlds
  17 (2022): 59–72. https://doi.org/10.1553/medievalworlds_no17_2022s59."
gibsonLabelingReligiousAffiliation2020: "———. “Labeling Religious Affiliation in Ibn
  Abī Uṣaybiʿa’s History of Physicians: A Quest.” December 11, 2020. https://tinyurl.com/gibson201211."
gibsonLabelingReligiousAffiliation2023: 'Dücker, Malte. “‘Je größer die Liebe und
  Nähe (zwischen Nachbarn), desto mehr Hass und Entfremdung kann es geben.’ : Interview
  zur Berufung von Prof. Dr. Nathan Gibson.” Jahrbuch des Fachbereichs Evangelische
  Theologie der Goethe-Universität Frankfurt am Main 3 (2023): 32–33. https://doi.org/10.21248/gups.80437.'
gibsonLinkingSyriacChristian2022: "———. “Linking Syriac and Christian Arabic Scholars
  to Their Multi-Religious Networks.” July 4, 2022. http://npgibson.com/s/syriacnetworks."
gibsonManuscriptCataloguesHandbook17: "“Academia.Edu.” Accessed April 1, 2017. https://www.academia.edu/29147134/From_manuscript_catalogues_to_a_handbook_of_Syriac_literature_Modeling_an_infrastructure_for_Syriaca.org."
gibsonMiaphysiteArabianTriangle2013: "———. “The Miaphysite Arabian Triangle: Ghassānīya-Ḥirtā-Najrān
  in the Sixth Century C.E.” March 15, 2013."
gibsonMidNinthCenturyArabicTranslation2017: "“Academia.Edu.” Accessed April 1, 2017.
  https://www.academia.edu/30958504/A_Mid-Ninth-Century_Arabic_Translation_of_Isaiah_Glimpses_from_al-Jahiz."
gibsonModelingBodyLiterature[acceptedrevisionsinpreparation]: "“Academia.Edu.” Accessed
  April 1, 2017. https://www.academia.edu/29147134/From_manuscript_catalogues_to_a_handbook_of_Syriac_literature_Modeling_an_infrastructure_for_Syriaca.org."
gibsonModelingBodyLiterature2016: "“Academia.Edu.” Accessed April 1, 2017. https://www.academia.edu/29147134/From_manuscript_catalogues_to_a_handbook_of_Syriac_literature_Modeling_an_infrastructure_for_Syriaca.org."
gibsonModelingBodyLiterature2016a: "———. “Modeling a Body of Literature in TEI: Bibliotheca
  Hagiographica Syriaca Electronica.” September 26, 2016. http://tei2016.acdh.oeaw.ac.at/poster-gallery."
gibsonMountainsPlainsGeographical2011: "———. “Mountains and Plains: Geographical Exegesis
  in ‘On Solitaries.’” June 26, 2011."
gibsonMultireligiousMultilingualKnowledge2021: "———. “Multireligious & Multilingual
  Knowledge Communities in Ibn Abī Uṣaybiʿa’s History of Physicians An Exploration
  Using Digital Tools.” May 18, 2021. https://tinyurl.com/gibson210518."
gibsonNeighborhoodBiblesCirculation2024: "“Full Text PDF.” Accessed March 18, 2024.
  http://publikationen.ub.uni-frankfurt.de/files/80437/09_Gibson_Duecker.pdf."
gibsonNetworksBiblicalScholarship2017: "“Balisage.” Accessed March 31, 2017. http://www.balisage.net/Proceedings/vol16/html/Gibson01/BalisageVol16-Gibson01.html."
gibsonNewHandbookSyriac2016: "“Academia.Edu.” Accessed April 1, 2017. https://www.academia.edu/29147134/From_manuscript_catalogues_to_a_handbook_of_Syriac_literature_Modeling_an_infrastructure_for_Syriaca.org."
gibsonNewHandbookSyriac2016a: "———. “The New Handbook of Syriac Literature: Bringing
  Syriac Literature into the Digital Landscape.” August 19, 2016."
gibsonPhysiciansPhilosophersPolymaths2017: "“Balisage.” Accessed March 31, 2017. http://www.balisage.net/Proceedings/vol16/html/Gibson01/BalisageVol16-Gibson01.html."
gibsonReadingHistoryPolemic2015: "———. “Reading History from Polemic: Al-Jāḥiẓ’s Portrayal
  of Christians in Abbasid Society.” October 13, 2015."
gibsonReadingLinesMining2017: "“Balisage.” Accessed March 31, 2017. http://www.balisage.net/Proceedings/vol16/html/Gibson01/BalisageVol16-Gibson01.html."
gibsonRhetoricFulcrumPower2016: "———. “Rhetoric as a Fulcrum of Power: How a Writer’s
  Words Helped the Caliph Turn Program into Practice.” April 8, 2016."
gibsonRobustDigitalApproaches2017: "“Balisage.” Accessed March 31, 2017. http://www.balisage.net/Proceedings/vol16/html/Gibson01/BalisageVol16-Gibson01.html."
gibsonScholarConvertsHubsKnowledge2018: 'Dücker, Malte. “‘Je größer die Liebe und
  Nähe (zwischen Nachbarn), desto mehr Hass und Entfremdung kann es geben.’ : Interview
  zur Berufung von Prof. Dr. Nathan Gibson.” Jahrbuch des Fachbereichs Evangelische
  Theologie der Goethe-Universität Frankfurt am Main 3 (2023): 32–33. https://doi.org/10.21248/gups.80437.'
gibsonSocialLivesPolemicists2023: 'Dücker, Malte. “‘Je größer die Liebe und Nähe (zwischen
  Nachbarn), desto mehr Hass und Entfremdung kann es geben.’ : Interview zur Berufung
  von Prof. Dr. Nathan Gibson.” Jahrbuch des Fachbereichs Evangelische Theologie der
  Goethe-Universität Frankfurt am Main 3 (2023): 32–33. https://doi.org/10.21248/gups.80437.'
gibsonStateArabicManuscript2018: 'Dücker, Malte. “‘Je größer die Liebe und Nähe (zwischen
  Nachbarn), desto mehr Hass und Entfremdung kann es geben.’ : Interview zur Berufung
  von Prof. Dr. Nathan Gibson.” Jahrbuch des Fachbereichs Evangelische Theologie der
  Goethe-Universität Frankfurt am Main 3 (2023): 32–33. https://doi.org/10.21248/gups.80437.'
gibsonTEIManuscriptDescription2019: 'Dücker, Malte. “‘Je größer die Liebe und Nähe
  (zwischen Nachbarn), desto mehr Hass und Entfremdung kann es geben.’ : Interview
  zur Berufung von Prof. Dr. Nathan Gibson.” Jahrbuch des Fachbereichs Evangelische
  Theologie der Goethe-Universität Frankfurt am Main 3 (2023): 32–33. https://doi.org/10.21248/gups.80437.'
gibsonThinkingTYaReorienting2019: 'Dücker, Malte. “‘Je größer die Liebe und Nähe (zwischen
  Nachbarn), desto mehr Hass und Entfremdung kann es geben.’ : Interview zur Berufung
  von Prof. Dr. Nathan Gibson.” Jahrbuch des Fachbereichs Evangelische Theologie der
  Goethe-Universität Frankfurt am Main 3 (2023): 32–33. https://doi.org/10.21248/gups.80437.'
gibsonTransculturationNeoculturationJewish2023: 'Dücker, Malte. “‘Je größer die Liebe
  und Nähe (zwischen Nachbarn), desto mehr Hass und Entfremdung kann es geben.’ :
  Interview zur Berufung von Prof. Dr. Nathan Gibson.” Jahrbuch des Fachbereichs Evangelische
  Theologie der Goethe-Universität Frankfurt am Main 3 (2023): 32–33. https://doi.org/10.21248/gups.80437.'
gibsonTurningFriendsEnemies2016: "———. “Turning Friends into Enemies and Enemies into
  Friends: Al-Jahiz’s Attempt to Redefine Religious Identity in Ninth-Century Iraq.”
  March 7, 2016."
gibsonUsaybianetDataStructure2023: 'Dücker, Malte. “‘Je größer die Liebe und Nähe
  (zwischen Nachbarn), desto mehr Hass und Entfremdung kann es geben.’ : Interview
  zur Berufung von Prof. Dr. Nathan Gibson.” Jahrbuch des Fachbereichs Evangelische
  Theologie der Goethe-Universität Frankfurt am Main 3 (2023): 32–33. https://doi.org/10.21248/gups.80437.'
gibsonWhatDidAlJahiz2016: "———. “What Did Al-Jāḥiẓ Know about Christians? Terms, Doctrines,
  and Practices in the Works of a IXth c. Muslim.” August 21, 2016."
goetheuniversitaetGoetheUniStelltSich2025: GoetheUniversitaet. Die Goethe-Uni Stellt
  Sich Vor, 2025. https://www.youtube.com/watch?v=7UJjxjlSKDU.
goetheuniversitaetNewlyAppointedProf2024: "———. Newly Appointed: Prof. Dr. Nathan
  Gibson, Professor of Religious Studies, 2024. https://www.youtube.com/watch?v=GuUZvtPNc4U."
InterviewDrNathan2021: "“Snapshot.” Accessed September 15, 2021. https://digitalorientalist.com/2021/09/14/interview-with-dr-nathan-p-gibson-about-syriaca-org-part-1/."
j.jacobUniversitaetTrifftGesellschaft2025: 'j.jacob. “Universität trifft Gesellschaft:
  Studierende präsentieren Poster zu interreligiösen Begegnungen in digitalen Räumen
  in der Evangelischen Akademie Frankfurt.” Islam & Digitality, February 12, 2025.
  https://islamdigitality.com/de/universitaet-trifft-gesellschaft-studierende-praesentieren-poster-zu-interreligioesen-begegnungen-in-digitalen-raeumen-in-der-evangelischen-akademie-frankfurt/.'
lohrScholarsServantsCaliphs2021: 'Löhr, Nadine, and Nathan P. Gibson. “Scholars, Servants
  and Caliphs: Encoding Social Encounters from Biographies.” Poster, June 18, 2021.
  https://prezi.com/view/jGuqpCUCKNtfUKB2YrXN/.'
michelsonGuideSyriacAuthors2016: 'Michelson, David A., and Nathan P. Gibson, eds.
  A Guide to Syriac Authors. The Syriac Biographical Dictionary 2. Syriaca.org: The
  Syriac Reference Portal, 2016. http://syriaca.org/authors.'
michelsonSyriacBiographicalDictionary2016: 'Michelson, David A., and Nathan P. Gibson,
  eds. A Guide to Syriac Authors. The Syriac Biographical Dictionary 2. Syriaca.org:
  The Syriac Reference Portal, 2016. http://syriaca.org/authors.'
plattInquiringBeelzebubTimothy2018: 'Platt, Andrew, and Nathan P. Gibson. “Inquiring
  of ‘Beelzebub’: Timothy and al-Jāḥiẓ on Christians in the ʿAbbāsid Legal System.”
  In Heirs of the Apostles: Studies on Arabic Christianity in Honor of Sidney H. Griffith,
  edited by David Bertaina, Sandra Toenies Keating, Mark N. Swanson, and Alexander
  Treiger, 254–81. Arabic Christianity 1. Leiden: Brill, 2018. https://doi.org/10.1163/9789004383869_013.'
pohlKnowledgeCollaborationJews2022: "———. “Knowledge Collaboration among Jews, Christians,
  Zoroastrians, and Muslims in the Abbasid Near East: Introduction.” Medieval Worlds
  17 (2022): 59–72. https://doi.org/10.1553/medievalworlds_no17_2022s59."
pohlKnowledgeCollaborationJews2023: "———. “Knowledge Collaboration among Jews, Christians,
  Zoroastrians, and Muslims in the Abbasid Near East: Introduction.” Medieval Worlds
  17 (2022): 59–72. https://doi.org/10.1553/medievalworlds_no17_2022s59."
sane-digitalAmbivalenteBeziehungenFachtag2023: SANE-Digital. Ambivalente Beziehungen
  - Fachtag - Interviews, 2023. https://www.youtube.com/watch?v=BhuS0hZfoSs.
schwartzModelingBornDigitalFactoid2021: Schwartz, Daniel L., Nathan P. Gibson, and
  Katayoun Torabi. “Modeling a Born-Digital Factoid Prosopography Using the TEI and
  Linked Data.” October 27, 2021. https://doi.org/10.5281/zenodo.6539718.
schwartzModelingBornDigitalFactoid2022a: Schwartz, Daniel L., Nathan P. Gibson, and
  Katayoun Torabi. “Modeling a Born-Digital Factoid Prosopography Using the TEI and
  Linked Data.” October 27, 2021. https://doi.org/10.5281/zenodo.6539718.
textandtransmissionjointresearchseminarTeTraNathanGibson2022: "———. “Circumnavigating
  Jewish and Christian Realities: What the Polemicist al-Jāḥiẓ Didn’t Want to Admit
  about His Society.” November 11, 2022. http://npgibson.com/s/circumnavigating."
TurmoilDisplacesMiddle: "“Snapshot.” Accessed September 15, 2021. https://www.wuwm.com/podcast/lake-effect-segments/2017-05-24/as-turmoil-displaces-middle-eastern-christians-scholars-work-to-preserve-syriac-culture."
vollandtBibliographyArabicBible2018: 'Vollandt, Ronny, and Nathan P. Gibson, eds.
  Bibliography of the Arabic Bible: A Classified and Annotated History of Scholarship.
  Munich: Biblia-Arabica.com, 2018. https://biblia-arabica.com/bibl.'
wolframHeimlichesVorbild2022: "“Snapshot.” Accessed January 23, 2023. https://www.juedische-allgemeine.de/kultur/heimliches-vorbild/?amp."
