---
ConnectingLateAntiquities2025: H-Soz-Kult. Kommunikation und Fachinformation für die
  Geschichtswissenschaften. “Connecting Late Antiquities | H-Soz-Kult. Kommunikation
  und Fachinformation für die Geschichtswissenschaften | Geschichte im Netz | History
  in the web.” H-Soz-Kult, May 19, 2025. https://www.hsozkult.de/conferencereport/id/fdkn-155043.
duckerJeGrosserLiebe2023: 'Dücker, Malte. “‘Je größer die Liebe und Nähe (zwischen
  Nachbarn), desto mehr Hass und Entfremdung kann es geben.’ : Interview zur Berufung
  von Prof. Dr. Nathan Gibson.” Jahrbuch des Fachbereichs Evangelische Theologie der
  Goethe-Universität Frankfurt am Main 3 (2023): 32–33. https://doi.org/10.21248/gups.80437.'
ghorbaninejadRighttoLeftRTLText2023: 'Ghorbaninejad, Masoud, Nathan P. Gibson, and
  David Joseph Wrisley. “Right-to-Left (RTL) Text: Digital Humanists Plus Half a Billion
  Users.” In Debates in the Digital Humanities 2023, edited by Matthew K. Gold and
  Lauren F. Klein, 47–73. Debates in the Digital Humanities 9. Minneapolis: University
  of Minnesota Press, 2023. https://dhdebates.gc.cuny.edu/read/debates-in-the-digital-humanities-2023/section/51ad75ab-76a4-43f3-81f8-0b31e350ca9c#ch03.'
gibsonAuthorityRecordsFrontiers2021: 'Gibson, Nathan P. “Authority Records at the
  Frontiers of Research: How Can Small Projects Incorporate Large Providers into Their
  Workflows?” October 28, 2021. http://npgibson.com/s/authority-frontiers.'
gibsonBibleArabicUpdate2018: 'Gibson, Nathan P., Miriam L. Hjälm, Peter Tarras, Ronny
  Vollandt, and Vevian Zaki. “The Bible in Arabic: An Update on the State of Research.”
  In Between the Cross and the Crescent: Studies in Honor of Samir Khalil Samir, S.J.
  on the Occasion of His Eightieth Birthday, edited by Željko Paša, 57–84. Orientalia
  Christiana Analecta 304. Rome: Pontifical Oriental Institute, 2018. https://doi.org/10.5282/ubm/epub.49819.'
gibsonChallengesPolyvalentInfrastructures2017: 'Gibson, Nathan P. “Challenges of Polyvalent
  Infrastructures: The Case of Syriac Studies and Syriaca.Org.” February 22, 2017.
  http://goo.gl/v6up1E.'
gibsonChristianOrientIslamic2017: 'Gibson, Nathan P. “The Christian Orient in Islamic
  Sources: Discovering Interdisciplinary Connections on the Digital Frontier.” September
  19, 2017. https://tinyurl.com/gibson170919.'
gibsonCircumnavigatingJewishChristian2022: 'Gibson, Nathan P. “Circumnavigating Jewish
  and Christian Realities: What the Polemicist al-Jāḥiẓ Didn’t Want to Admit about
  His Society.” November 11, 2022. http://npgibson.com/s/circumnavigating.'
gibsonClosestFriendshipAlJahiz2015: Gibson, Nathan P. “Closest in Friendship? Al-Jahiz’
  Profile of Christians in Abbasid Society in ‘The Refutation of Christians’ (‘Al-Radd
  'ala al-Nasara’).” Ph.D. dissertation, The Catholic University of America, 2015.
  http://search.proquest.com/docview/1691345901.
gibsonCommunitiesKnowledgeInterreligious2020: 'Gibson, Nathan P., ed. Communities
  of Knowledge: Interreligious Networks of Scholars in Ibn Abi Usaybiʿa’s History
  of the Physicians. Version 0.4. Munich: Usaybia.net, 2020. https://doi.org/10.5281/zenodo.3975505.'
gibsonCommunitiesKnowledgeInterreligious2023a: 'Gibson, Nathan P., and Robin Schmahl.
  “Communities of Knowledge: Interreligious Networks of Scholars in Ibn Abī Uṣaybiʿa’s History
  of the Physicians (Project Report).” Medieval Worlds 18 (July 2023): 196–218. https://doi.org/10.1553/medievalworlds_no18_2023s196.'
gibsonCrosscommunalScholarlyInteractions2022: 'Gibson, Nathan P., and Ronny Vollandt.
  “Cross-Communal Scholarly Interactions.” In Routledge Handbook on the Sciences in
  Islamicate Societies: Practices from the 2nd/8th to the 13th/19th Centuries, edited
  by Sonja Brentjes, Peter Barker, and Rana Brentjes, 723–40. Routledge Handbooks.
  London: Routledge, 2022. https://doi.org/10.4324/9781315170718-65.'
gibsonCyberinfrastructureSyriacLiterature2017: 'Gibson, Nathan P. “Toward a Cyberinfrastructure
  for Syriac Literature: Mapping a Text Corpus Using TEI and RDF.” January 24, 2017.
  http://hdl.handle.net/11858/00-1780-0000-002C-93A4-1.'
gibsonDivineAdoptionJewish2023: 'Gibson, Nathan P. “Divine Adoption in Jewish, Christian,
  and Muslim Scriptures: Al-Jāḥiẓ’s View.” Invited, July 20, 2023. https://npgibson.com/s/adoption.'
gibsonEncodingWesternNonWestern2015: "“Balisage.” Accessed March 31, 2017. http://www.balisage.net/Proceedings/vol16/html/Gibson01/BalisageVol16-Gibson01.html."
gibsonEntityTaggingNetwork2024: Gibson, Nathan P. “Entity Tagging and Network Extraction
  in Arabic Texts.” Invited, June 24, 2024. https://github.com/SunoikisisDC/SunoikisisDC-2023-2024/wiki/11.-Arabic-Georgian.
gibsonFiveCenturiesHistory2019: Gibson, Nathan P. “Five Centuries of History in a
  Network.” September 20, 2019. https://doi.org/10.5281/zenodo.3452744.
gibsonKnowledgeCollaborationJews2022: 'Gibson, Nathan P. “Knowledge Collaboration
  among Jews, Christians, Zoroastrians, and Muslims in the Abbasid Near East: Introduction.”
  Medieval Worlds 17 (2022): 59–72. https://doi.org/10.1553/medievalworlds_no17_2022s59.'
gibsonLabelingReligiousAffiliation2020: 'Gibson, Nathan P. “Labeling Religious Affiliation
  in Ibn Abī Uṣaybiʿa’s History of Physicians: A Quest.” December 11, 2020. https://tinyurl.com/gibson201211.'
gibsonLabelingReligiousAffiliation2023: 'Gibson, Nathan P. “Labeling Religious Affiliation
  in Ibn Abī Uṣaybiʿa’s History of Physicians: A Quest.” Medieval Worlds 18 (July
  2023): 246–70. https://doi.org/10.1553/medievalworlds_no18_2023s246.'
gibsonLinkingSyriacChristian2022: Gibson, Nathan P. “Linking Syriac and Christian
  Arabic Scholars to Their Multi-Religious Networks.” July 4, 2022. http://npgibson.com/s/syriacnetworks.
gibsonManuscriptCataloguesHandbook17: 'Gibson, Nathan P., David A. Michelson, and
  Daniel L. Schwartz. “From Manuscript Catalogues to a Handbook of Syriac Literature:
  Modeling an Infrastructure for Syriaca.Org.” Journal of Data Mining and Digital
  Humanities Special Issue on Computer-Aided Processing of Intertextuality in Ancient
  Languages (May 30, 2017). https://doi.org/10.46298/jdmdh.1395.'
gibsonMidNinthCenturyArabicTranslation2017: 'Gibson, Nathan P. “A Mid-Ninth-Century
  Arabic Translation of Isaiah? Glimpses from al-Jāḥiẓ.” In Senses of Scripture, Treasures
  of Tradition: The Bible in Arabic among Jews, Christians and Muslims, edited by
  Miriam Lindgren Hjälm, 327–69. Biblia Arabica 5. Leiden: Brill, 2017. https://doi.org/10.1163/9789004347403_015.'
gibsonModelingBodyLiterature[acceptedrevisionsinpreparation]: 'Gibson, Nathan P.,
  and David A. Michelson. “Modeling a Body of Literature in TEI: The New Handbook
  of Syriac Literature.” Journal of the Text Encoding Initiative, [accepted, revisions
  in preparation]. https://doi.org/10.17613/M6V67M.'
gibsonModelingBodyLiterature2016: 'Gibson, Nathan P., and David A. Michelson. “Modeling
  a Body of Literature in TEI: The New Handbook of Syriac Literature.” Vienna, Austria,
  2016. http://tei2016.acdh.oeaw.ac.at/poster-gallery.'
gibsonModelingBodyLiterature2016a: 'Gibson, Nathan P., and David A. Michelson. “Modeling
  a Body of Literature in TEI: The New Handbook of Syriac Literature.” Vienna, Austria,
  2016. http://tei2016.acdh.oeaw.ac.at/poster-gallery.'
gibsonMultireligiousMultilingualKnowledge2021: Gibson, Nathan P. “Multireligious &
  Multilingual Knowledge Communities in Ibn Abī Uṣaybiʿa’s History of Physicians An
  Exploration Using Digital Tools.” May 18, 2021. https://tinyurl.com/gibson210518.
gibsonNeighborhoodBiblesCirculation2024: 'Gibson, Nathan P. “Neighborhood Bibles:
  The Circulation of Tanakh/OT Versions Among Arabic Muslim Writers (8th–10th Century).”
  Invited, April 29, 2024. https://npgibson.com/s/neighborhood.'
gibsonNetworksBiblicalScholarship2017: 'Gibson, Nathan P. “Networks of Biblical Scholarship:
  Jewish, Christian, and Muslim Collaboration in Biographical Literature.” November
  7, 2017. https://tinyurl.com/gibson171107.'
gibsonNewHandbookSyriac2016: 'Gibson, Nathan P., David A. Michelson, and Jeanne-Nicole
  Mellon Saint-Laurent, eds. The New Handbook of Syriac Literature. Syriaca.org: The
  Syriac Reference Portal, 2016. http://syriaca.org/nhsl.'
gibsonRobustDigitalApproaches2017: 'Gibson, Nathan P. “Robust Digital Approaches to
  Literary History: The Case of Syriac.” May 27, 2017. https://goo.gl/4MYc2X.'
gibsonScholarConvertsHubsKnowledge2018: Gibson, Nathan P. “Scholar-Converts as Hubs
  of Knowledge Exchange in the Medieval Islamicate World.” June 12, 2018. https://tinyurl.com/gibson180612.
gibsonSocialLivesPolemicists2023: Gibson, Nathan P. “The Social Lives of Polemicists.”
  Inaugural Lecture, November 1, 2023. https://npgibson.com/s/social-lives.
gibsonStateArabicManuscript2018: Gibson, Nathan P. “State of Arabic Manuscript Description.”
  October 5, 2018. https://tinyurl.com/ba181005.
gibsonThinkingTYaReorienting2019: 'Gibson, Nathan P. “Thinking in ⅃TЯ: Reorienting
  the Directional Assumptions of Global Digital Scholarship.” June 8, 2019. https://doi.org/10.17613/3vws-5s29.'
gibsonTransculturationNeoculturationJewish2023: Gibson, Nathan P. “Transculturation
  & Neoculturation among Jewish Physicians in Fatimid Cairo.” February 8, 2023. http://npgibson.com/s/transculturation.
goetheuniversitaetGoetheUniStelltSich2025: GoetheUniversitaet. Die Goethe-Uni Stellt
  Sich Vor, 2025. https://www.youtube.com/watch?v=7UJjxjlSKDU.
goetheuniversitaetNewlyAppointedProf2024: 'GoetheUniversitaet. Newly Appointed: Prof.
  Dr. Nathan Gibson, Professor of Religious Studies, 2024. https://www.youtube.com/watch?v=GuUZvtPNc4U.'
InterviewDrNathan2021: "“Snapshot.” Accessed September 15, 2021. https://digitalorientalist.com/2021/09/14/interview-with-dr-nathan-p-gibson-about-syriaca-org-part-1/."
j.jacobUniversitaetTrifftGesellschaft2025: "“Snapshot.” Accessed March 14, 2025. https://islamdigitality.com/de/universitaet-trifft-gesellschaft-studierende-praesentieren-poster-zu-interreligioesen-begegnungen-in-digitalen-raeumen-in-der-evangelischen-akademie-frankfurt/."
lohrScholarsServantsCaliphs2021: 'Löhr, Nadine, and Nathan P. Gibson. “Scholars, Servants
  and Caliphs: Encoding Social Encounters from Biographies.” Poster, June 18, 2021.
  https://prezi.com/view/jGuqpCUCKNtfUKB2YrXN/.'
michelsonGuideSyriacAuthors2016: 'Michelson, David A., and Nathan P. Gibson, eds.
  A Guide to Syriac Authors. The Syriac Biographical Dictionary 2. Syriaca.org: The
  Syriac Reference Portal, 2016. http://syriaca.org/authors.'
michelsonSyriacBiographicalDictionary2016: 'Michelson, David A., Jeanne-Nicole Mellon
  Saint-Laurent, Nathan P. Gibson, and Daniel L. Schwartz, eds. The Syriac Biographical
  Dictionary. Syriaca.org: The Syriac Reference Portal, 2016. http://syriaca.org/persons.'
plattInquiringBeelzebubTimothy2018: 'Platt, Andrew, and Nathan P. Gibson. “Inquiring
  of ‘Beelzebub’: Timothy and al-Jāḥiẓ on Christians in the ʿAbbāsid Legal System.”
  In Heirs of the Apostles: Studies on Arabic Christianity in Honor of Sidney H. Griffith,
  edited by David Bertaina, Sandra Toenies Keating, Mark N. Swanson, and Alexander
  Treiger, 254–81. Arabic Christianity 1. Leiden: Brill, 2018. https://doi.org/10.1163/9789004383869_013.'
pohlKnowledgeCollaborationJews2022: 'Gibson, Nathan P. “Knowledge Collaboration among
  Jews, Christians, Zoroastrians, and Muslims in the Abbasid Near East: Introduction.”
  Medieval Worlds 17 (2022): 59–72. https://doi.org/10.1553/medievalworlds_no17_2022s59.'
pohlKnowledgeCollaborationJews2023: 'Pohl, Walter, Andre Gingrich, and Nathan P. Gibson,
  eds. “Knowledge Collaboration among Jews, Christians, Zoroastrians, and Muslims
  in the Abbasid Near East II [Thematic Section].” Medieval Worlds 18 (July 2023):
  137–270. https://doi.org/10.1553/medievalworlds_no18_2023.'
sane-digitalAmbivalenteBeziehungenFachtag2023: SANE-Digital. Ambivalente Beziehungen
  - Fachtag - Interviews, 2023. https://www.youtube.com/watch?v=BhuS0hZfoSs.
schwartzModelingBornDigitalFactoid2021: Schwartz, Daniel L., Nathan P. Gibson, and
  Katayoun Torabi. “Modeling a Born-Digital Factoid Prosopography Using the TEI and
  Linked Data.” October 27, 2021. https://doi.org/10.5281/zenodo.6539718.
schwartzModelingBornDigitalFactoid2022a: Schwartz, Daniel L., Nathan P. Gibson, and
  Katayoun Torabi. “Modeling a Born-Digital Factoid Prosopography Using the TEI and
  Linked Data.” Journal of the Text Encoding Initiative Rolling Issue (2022). https://doi.org/10.4000/jtei.3979.
textandtransmissionjointresearchseminarTeTraNathanGibson2022: Text and Transmission
  Joint Research Seminar. TeTra | Nathan Gibson “Circumnavigating Jewish and Christian
  Realities,” 2022. https://www.youtube.com/watch?v=kCKxoCkRxs0.
TurmoilDisplacesMiddle: "“Snapshot.” Accessed September 15, 2021. https://www.wuwm.com/podcast/lake-effect-segments/2017-05-24/as-turmoil-displaces-middle-eastern-christians-scholars-work-to-preserve-syriac-culture."
vollandtBibliographyArabicBible2018: 'Vollandt, Ronny, and Nathan P. Gibson, eds.
  Bibliography of the Arabic Bible: A Classified and Annotated History of Scholarship.
  Munich: Biblia-Arabica.com, 2018. https://biblia-arabica.com/bibl.'
wolframHeimlichesVorbild2022: Wolfram, Gernot. “Heimliches Vorbild.” Jüdische Allgemeine,
  November 30, 2022. https://www.juedische-allgemeine.de/kultur/heimliches-vorbild/.
