#!/usr/bin/env ruby
# frozen_string_literal: true

# extract_image_credits.rb
#
# Reads XMP metadata from .xmp sidecars generated by Darktable.
# Extracts Dublin Core (DC) fields and writes to _data/image_credits.yaml.
# Only images with an .xmp sidecar are processed.
# Merges with any existing YAML entries (XMP wins for images it covers).
#
# Requires: exiftool (brew install exiftool / apt-get install libimage-exiftool-perl)
# Run from the repo root.
#
# Usage:
#   ruby scripts/extract_image_credits.rb           # scan and write
#   ruby scripts/extract_image_credits.rb --dry-run # print YAML without writing

require 'yaml'
require 'json'
require 'open3'
require 'fileutils'

class ImageCreditExtractor
  IMG_DIR       = 'img'
  IMG_GLOB      = File.join(IMG_DIR, '**', '*.jpg')
  OUTPUT_FILE   = '_data/image_credits.yaml'

  # XMP DC field mapping
  XMP_DC_FIELDS = {
    'Description'  => 'description',  # dc:description
    'Creator'      => 'creator',      # dc:creator (array)
    'Identifier'   => 'identifier',   # dc:identifier
    'Publisher'    => 'publisher',    # dc:publisher (array)
    'Source'       => 'source_url',   # dc:source
    'Rights'       => 'rights'        # dc:rights
  }.freeze

  def initialize(dry_run: false)
    @dry_run   = dry_run
    @updated   = 0
    @skipped   = 0
    @no_sidecar = 0
    @errors    = 0
  end

  def run
    unless exiftool_available?
      warn 'ERROR: exiftool not found. Install with: brew install exiftool'
      exit 1
    end

    images = Dir.glob(IMG_GLOB)
    puts "Scanning #{images.size} image(s) in #{IMG_DIR}/"

    credits = load_existing

    images.each do |path|
      xmp_path = "#{path}.xmp"
      unless File.exist?(xmp_path)
        @no_sidecar += 1
        next
      end

      entry = read_xmp(xmp_path)
      next if entry.nil? || entry.empty?

      key = File.basename(path, '.*')
      credits[key] = entry
      puts "  [READ] #{key} (#{entry.keys.join(', ')})"
      @updated += 1
    end

    if @dry_run
      puts "\n--- DRY RUN: would write to #{OUTPUT_FILE} ---"
      puts credits.to_yaml
    else
      FileUtils.mkdir_p(File.dirname(OUTPUT_FILE))
      File.write(OUTPUT_FILE, credits.to_yaml)
      puts "\nWrote #{credits.size} total entries to #{OUTPUT_FILE}"
    end

    print_summary
  end

  private

  def exiftool_available?
    system('exiftool -ver > /dev/null 2>&1')
  end

  def read_xmp(xmp_path)
    cmd = ['exiftool', '-G1', '-s', '-n', xmp_path]
    output, status = Open3.capture2(*cmd)

    unless status.success?
      warn "  [ERROR] exiftool failed for #{xmp_path}"
      @errors += 1
      return nil
    end

    entry = parse_xmp_output(output)
    entry.empty? ? nil : entry
  rescue StandardError => e
    warn "  [ERROR] #{xmp_path}: #{e.message}"
    @errors += 1
    nil
  end

  def parse_xmp_output(output)
    entry = {}
    lines = output.split("\n")

    # Parse exiftool output format: [TAG_FAMILY] TAG_NAME : VALUE
    dc_fields = {}

    lines.each do |line|
      next unless line.include?('[XMP-dc]')

      # Extract field name and value
      if line =~ /\[XMP-dc\]\s+(\w+)\s*:\s*(.*)/
        field_name = Regexp.last_match(1)
        field_value = Regexp.last_match(2).strip

        next if field_value.empty?

        # Group multi-valued fields (Creator, Publisher)
        dc_fields[field_name] ||= []
        dc_fields[field_name] << field_value
      end
    end

    # Map XMP fields to YAML keys
    XMP_DC_FIELDS.each do |xmp_key, yaml_key|
      if dc_fields[xmp_key]
        values = dc_fields[xmp_key]
        # Join arrays with semicolon, take first for single values
        entry[yaml_key] = if values.size > 1
                            values.join('; ')
                          else
                            values.first
                          end
      end
    end

    entry
  end

  def load_existing
    return {} unless File.exist?(OUTPUT_FILE)

    YAML.load_file(OUTPUT_FILE) || {}
  rescue StandardError => e
    warn "WARNING: Could not load #{OUTPUT_FILE}: #{e.message}"
    {}
  end

  def print_summary
    puts "\n" + '=' * 50
    puts "IMAGE CREDIT EXTRACTION SUMMARY"
    puts '=' * 50
    puts "Mode:        #{@dry_run ? 'DRY RUN' : 'WRITE'}"
    puts "Source:      XMP sidecars (.xmp files)"
    puts "Updated:     #{@updated}"
    puts "No sidecar:  #{@no_sidecar}"
    puts "Errors:      #{@errors}"
    puts '=' * 50
    puts "Output:      #{OUTPUT_FILE}" unless @dry_run
  end
end

if __FILE__ == $PROGRAM_NAME
  dry_run = ARGV.include?('--dry-run')
  ImageCreditExtractor.new(dry_run: dry_run).run
end
